-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Erstellungszeit: 20. Jul 2022 um 13:03
-- Server-Version: 10.4.24-MariaDB
-- PHP-Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `testzwecke`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `linksafe`
--

CREATE TABLE `linksafe` (
  `id` int(11) NOT NULL,
  `titel` varchar(150) NOT NULL,
  `description` varchar(1024) NOT NULL,
  `url` varchar(1024) NOT NULL,
  `image` varchar(255) NOT NULL,
  `category` varchar(255) NOT NULL,
  `advertising` varchar(5) NOT NULL,
  `clicks` int(11) NOT NULL,
  `date` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Daten für Tabelle `linksafe`
--

INSERT INTO `linksafe` (`id`, `titel`, `description`, `url`, `image`, `category`, `advertising`, `clicks`, `date`) VALUES
(1, 'free 3d', '„free3d“ ist eine umfangreiche Sammlung an 3d-Modellen in unterschiedlichen Formaten. es werden auch Modelle mit Animationen bzw. Skelett angeboten, sowie auch speziell für die Computerspiele-Entwicklung erstellte Modelle.', 'https://free3d.com', 'teaser_verweis_free3d.jpg', '3D-Material', 'false', 12, ''),
(2, 'Freizeitmagazin Royale', 'Die deutschen Freizeitmagazine und die dahinter stehenden Eigentümer werden hier mit ihren eigenen Mitteln des Journalismus konfrontiert und entblößt.', 'https://freizeitmagazinroyale.de/', 'teaser_verweis_fmroyal..jpg', 'Aufklärung', 'false', 37, ''),
(3, 'Frontext Files', 'Diese Seite „frontexfiles.eu“ ist eine Aufklärung des „ZDF Magazin Royale“ über die Aktivitäten der EU und dem Unternehmen Frontex, welches dafür eingesetzt wird Menschenrechtsverletzungen aller art im Auftrag der Europäischen Union durchzuführen.', 'https://frontexfiles.eu/', 'teaser_verweise_frontexfiles.jpg', 'Aufklärung', 'false', 11, ''),
(4, 'Geld und Wohlstand', 'In diesem Podcast sprechen Ole Nymoen und Wolfgang m. Schmitt über Geld und Wohlstand und klären über ökonomische Themen und Zusammenhänge auf.', 'https://wohlstandfueralle.podigee.io/', 'teaser_verweis_wohlstandfueralle.jpg', 'Aufklärung', 'false', 56, ''),
(5, 'Geld für die Welt', '„Geld für die Welt“ ist ein Newsletter von Maurice Höfgen, einem Ökonom und Autor des Buches „Mythos Geldknappheit“, der aufzeigt, wie falsch die etablierte Ökonomie denkt und handelt. Neben diesem Newsletter gibt es auch noch einen „YouTube“-Kanal mit gleichem Titel.', 'https://mauricehoefgen.substack.com/', 'teaser_verweis_geldfuerdiewelt.jpg', 'Aufklärung', 'false', 98, ''),
(6, 'unsplash', 'Bei \"unsplash\" sind alle Inhalte kostenlos und frei zugänglich. die Inhalte können für private und kommerzielle Projekte verwendet werden und es gibt keine Bedingungen, die eine Nutzung erlauben.', 'https://unsplash.com/', 'teaser_verweise_unsplash.jpg', 'Bildmaterial', 'false', 6, ''),
(7, 'pexels', 'Schöne und kostenlose Fotos und Videos, die ohne Einschränkungen nutzbar sind. Auch kostenlose Videos und mehr sind so verfügbar.', 'https://www.pexels.com/de-de/', 'teaser_verweise_pexels.jpg', 'Bildmaterial', 'false', 63, ''),
(8, 'Free Nature Stock', 'Sehr viele schöne Naturbilder und Videos für den privaten und kommerziellen Gebrauch finden Sie auf dieser Webseite, die Inhalte werden unter einer  \"CC0\" Lizenz veröffentlicht.', 'https://freenaturestock.com/', 'teaser_verweise_freenaturestock.jpg', 'Bildmaterial', 'false', 29, ''),
(9, 'Morgue File', '\"Morgue File\" bietet eine große Auswahl an kostenlosen Bildern, Videos, Vektorgrafiken und Templates.', 'https://morguefile.com/', 'teaser_verweise_morguefile.jpg', 'Bildmaterial', 'false', 21, ''),
(10, 'Public Domain Pictures', 'Ganz viele Bilder für umsonst und jeden erdenklichen Zweck. \"Public Domain\" bezeichnet gemeinfreie Inhalte, d. h. der Urheber verzichtet auf seine Rechte an dem/den Werk(en).', 'https://www.publicdomainpictures.net/', 'teaser_verweise_publicdomainpictures.jpg', 'Bildmaterial', 'false', 183, ''),
(11, 'Stocksnap', 'Kostenlose Bilder unter der \"CC0\"-Lizenz, frei von Urheberrechtsbedingungen.', 'https://stocksnap.io', 'teaser_verweise_stocksnap.io_.jpg', 'Bildmaterial', 'false', 92, ''),
(12, 'Clean PNG', 'Viele wunderschöne, kostenlose, hochaufgelöste und hintergrundfreie PNG-Dateien für private und kommerzielle Projekte.', 'https://de.cleanpng.com/', 'teaser_verweise_cleanpng.jpg', 'Bildmaterial', 'false', 43, ''),
(13, 'Style Stock', 'Kostenlose feminine Fotos für ihre Projekt. in Druckauflösung und eben kostenlos.', 'https://styledstock.co/', 'teaser_verweise_styledstock.jpg', 'Bildmaterial', 'false', 13, ''),
(14, 'BURST', 'Laden Sie kostenlose und hoch aufgelöste Fotos kostenlos für Ihre Projekte herunter.', 'https://burst.shopify.com/', 'teaser_verweise_burst.jpg', 'Bildmaterial', 'false', 11, ''),
(15, 'freestocks', 'Kostenlose Bilder für persönlichen oder kommerziellen Projekte.', 'https://freestocks.org/', 'teaser_verweise_freestocks.org_.jpg', 'Bildmaterial', 'false', 17, ''),
(16, 'Picography', 'Kostenlose Bilder für jeden Zweck: lizenzfrei und hoch aufgelöst.', 'https://picography.co/', 'teaser_verweise_picography.jpg', 'Bildmaterial', 'false', 21, ''),
(17, 'FOCA Stock', 'Kostenlose Fotos, Videos und Templates für kommerzielle Zwecke. (\"CC0\"-Lizenz)', 'https://focastock.com/', 'teaser_verweise_focastock.jpg', 'Bildmaterial', 'false', 195, ''),
(18, 'picjumbo', 'Wunderschöne kostenlose Fotos und Hintergründen in hoher Auflösung für den privaten und kommerziellen Gebrauch.', 'https://picjumbo.com/', 'teaser_verweise_picjumbo.jpg', 'Bildmaterial', 'false', 0, ''),
(19, 'pixabay', 'Über 2.5 Millionen Bilder in hoher Qualität und Auflösung, sogar Videos und Musik sind hier kostenlos erhältlich.', 'https://pixabay.com/', 'teaser_verweise_pixabay.jpg', 'Bildmaterial', 'false', 9, ''),
(20, 'NASA Images', 'Audio-, Video- und Bilddateien der NASA kostenlos für eigene Projekte verwenden.', 'https://images.nasa.gov/', 'teaser_verweise_nasa.jpg', 'Bildmaterial', 'false', 34, ''),
(21, 'Life of Pix', 'Kostenlos hochaufgelöste Fotos für jeden Verwendungszweck.', 'https://www.lifeofpix.com/', 'teaser_verweise_freehightresolution.jpg', 'Bildmaterial', 'false', 76, ''),
(22, 'Little Visuals', 'Super viele Fotos kostenlos für den kommerziellen Gebrauch.', 'https://littlevisuals.co/', 'teaser_verweise_littlevisuals.jpg', 'Bildmaterial', 'false', 3, ''),
(23, 'twnsnd', 'Eine Fotosammlung uralter Fotografien für den persönlichen Gebrauch.', 'https://nos.twnsnd.co/', 'teaser_verweise_newoldstock.jpg', 'Bildmaterial', 'false', 1, ''),
(24, 'Anyrgb', 'Sehr viele schöne Cliparts für diverse Zwecke.', 'https://www.anyrgb.com/', 'teaser_verweise_anyrgb.jpg', 'Bildmaterial', 'false', 1, ''),
(25, 'Skuawk', 'Viele lizenzfreie Fotos unter einer \"CC0\"-Lizenz.', 'https://skuawk.com/', 'teaser_verweise_skuawk.jpg', 'Bildmaterial', 'false', 6, ''),
(26, 'stockvault', 'Fotos, Texturen und Illustrationen (es gelten die dem Bild beigefügten Lizenzbedingungen) kostenlos herunterladbar.', 'https://www.stockvault.net/', 'teaser_verweise_stockvault.jpg', 'Bildmaterial', 'false', 8, ''),
(27, 'Foodiesfeed', 'Sehr als 1700 kostenlose Fotos von Mahlzeiten und Nahrungsmitteln warten auf Sie.', 'https://www.foodiesfeed.com/', 'teaser_verweise_foodiesfeed.jpg', 'Bildmaterial', 'false', 2, ''),
(28, 'GratisoGraphy', 'Die Bilder hier gibt es ohne Urheberrechtsbedingungen kostenlos.', 'https://gratisography.com/', 'teaser_verweise_gatisography.jpg', 'Bildmaterial', 'false', 62, ''),
(29, 'Pikwizard', 'Hochwertige, kostenlose Stockfotos: atemberaubende Bibliothek mit über 1 Million Bildern und Videos. gebührenfrei und sicher für die kommerzielle Nutzung, ohne dass eine Namensnennung erforderlich ist.', 'https://pikwizard.com/', 'teaser_verweise_pikwizard.jpg', 'Bildmaterial', 'false', 19, ''),
(30, 'Pepper and Carrot', '\"Pepper and Carrot\" ist eine Comicserie von David Revoy, einem Künstler, der überwiegend für digitale Kunstwerke freie software verwendet.', 'https://www.peppercarrot.com/', 'teaser_pepperandcarrot.jpg', 'Comic', 'false', 297, ''),
(31, 'Open Game Art', '„opengameart.org“ bietet eine große Auswahl an kostenlosen und frei verfügbaren „Assets“ für Computerspiele. von Musik bis hin zu 3D-Modellen.', 'https://opengameart.org/', 'teaser_verweis_opengameartorg.jpg', 'Computerspielmaterial', 'false', 37, ''),
(32, 'ZFA Medien', 'Der zentrale Fachausschuss für Medien ist die Anlaufstelle für Fachinformationen aller in der Medienbranche schaffenden.', 'https://zfamedien.de/', 'teaser_verweis_zfamedien.jpg', 'Information', 'false', 13, ''),
(33, 'ALT Codes', 'Eine Übersicht über die Zeichen, die via Tastatur mit der Alt-Taste erzeugt werden können.', 'https://www.alt-codes.net/', 'teaser_verweis_altcodes.jpg', 'Information', 'false', 19, ''),
(34, 'art-hm', 'Hursched Murodow´s Webseite: \"Kunst und Gestaltung sind seit frühester Jugend bestimmend für mich. angefangen hat alles mit \"Walt-Disney-Figuren\", die ich mit Bleistift gezeichnet habe ...\"', 'https://art-hm.de/', 'teaser_art-hm.com_.jpg', 'Künstler', 'false', 29, ''),
(35, 'Free Music Archive', 'Eine große Auswahl an kostenloser Musik für YouTube, Facebook und sonst noch was erwarten sie hier.', 'https://freemusicarchive.org/home', 'teaser_verweise_freemusicarchive.jpg', 'Musikmaterial', 'false', 11, ''),
(36, 'jami', '„jami“ ist eine freie und universelle Kommunikationsplattform, die die Privatsphäre und Freiheit der Benutzer schützt.', 'https://jami.net/', 'teaser_verweis_jami.jpg', 'Opensource', 'false', 61, ''),
(37, 'BeeRef', '„BeeRef“ ist ein kleines einfaches Programm um Referenzbilder anzuzeigen, zu arrangieren und minimal in den kreativen Arbeitsfluss einzugreifen.', 'https://beeref.org/', 'teaser_verweis_beeref.jpg', 'Opensource', 'false', 3, ''),
(38, 'Storyboarder', 'Dieses Programm macht es möglich einfach Geschichten zu visualisieren, die als Grundlage für Comics, Animationen oder Zwischensequenzen dienen.', 'https://wonderunit.com/storyboarder/', 'teaser_verweis_storyboarder.jpg', 'Opensource', 'false', 33, ''),
(39, 'Z-Anatomy', '„Z-Anatomy“ ist kein Programm, sondern eine Blender-Datei, die mit Blender genutzt werden kann. Es ist ein freier 3D-Atlas des menschlichen Körpers, der auch als App für das Handy verfügbar ist. ', 'https://www.z-anatomy.com/', 'teaser_verweis_zanatomy.jpg', 'Opensource', 'false', 39, ''),
(40, 'Matrial Maker', 'Um physikalisch basierende Anzeigen von Materialien in 3D-Anwendungen zu entwickeln, bietet sich „Material Maker“ an.', 'https://www.materialmaker.org/', 'teaser_verweis_matrialmaker.jpg', 'Opensource', 'false', 12, ''),
(41, 'FontForge', 'mit „FontForge“ lassen sich Fonts-Dateien erzeugen und erstellen. dabei bietet das Programm zahlreiche Möglichkeiten zur Bearbeitung der Topografie.', 'https://fontforge.org/', 'teaser_verweis_fontforge.jpg', 'Opensource', 'false', 79, ''),
(42, 'Milton', '„Milton“ ist ein kostenloses Zeichenprogramm mit einer unendlichen Leinwand, ebenen und einfacher Handhabung.', 'https://www.miltonpaint.com/', 'teaser_verweis_miltonpaint.jpg', 'Opensource', 'false', 43, ''),
(43, 'dupeGuru', 'Um Duplikate von Dateien zu finden, die sich auf der Festplatte verstecken und Speicherplatz unnötig verbrauchen, gibt es „dupeGuru“.', 'https://dupeguru.voltaicideas.net/', 'teaser_verweis_dupeguru.jpg', 'Opensource', 'false', 52, ''),
(44, 'overGrive', 'Der „google-Drive“ wird nicht nativ von „google“ unter „Linux“ unterstützt. „overGrive“ füllt diese Lücke.', 'https://www.thefanclub.co.za/overgrive/', 'teaser_verweis_overgrive.jpg', 'Opensource', 'false', 12, ''),
(45, 'Effekseer', 'Mit diesem Programm können sie leicht und schnell wundervolle Partikel-Effekte zu erzeugen, welche sich dann in „Unreal“, „Unity“ usw. verwenden lassen.', 'https://effekseer.github.io/en/index.html', 'teaser_verweis_effekseer.jpg', 'Opensource', 'false', 79, ''),
(46, 'openElement', '„openElement“ ist ein Editor zur Entwickelung und gestalten von Webseiten nach dem Prinzip: „was du siehst, bekommst du“.', 'http://openelement.uk/index.html', 'teaser_verweis_openelement.jpg', 'Opensource', 'false', 68, ''),
(47, 'Webcamoid', '„Webcamoid“ ist eine Anwendung, die in Zusammenarbeit mit einer „Webcam“ diverse Manipulationen zulässt.', 'https://webcamoid.github.io/', 'teaser_verweis_webcamoid.jpg', 'Opensource', 'false', 12, ''),
(48, 'Tahoma 2D', '„Tahoma 2D“ ist eine kostenlose und freie Anwendung zum Erzeugen von 2D Bewegungsanimationen.', 'https://tahoma2d.org/', 'teaser_verweis_tahoma2d.jpg', 'Opensource', 'false', 63, ''),
(49, 'Alicevision', 'Diese software ist eine Anwendung zur Fotogrammetrie (Wissenschaft der Messung von Fotografien), sie ist quelloffen und kostenlos.', 'https://alicevision.org/', 'teaser_verweis_alicevision.jpg', 'Opensource', 'false', 27, ''),
(50, 'ArmorPaint', '„ArmorPaint“ ist eine 3D-PBR-Malanwendung für Windows, Linux und macOS. Die kostenlose Variante muss selbst über den Quellcode kompiliert werden.', 'https://armorpaint.org/', 'teaser_verweis_amorpaint.jpg', 'Opensource', 'false', 103, ''),
(51, 'Krita', '„Krita“ ist die Anwendung, wenn es um zeichnen und malen geht. digitale Kunst ist dabei das Schlagwort, denn keine anderes Programm ist so vielseitig und nützlich.', 'https://krita.org/', 'teaser_verweis_krita.jpg', 'Opensource', 'false', 52, ''),
(52, 'Blender', '„Blender“ ist so umfangreich an Funktionen und Möglichkeiten für den Nutzer, dass es quasi den Industriestandard wie „Maya“ oder „Cinema4d“ abgelöst hat.', 'https://www.blender.org/', 'teaser_verweis_blender.jpg', 'Opensource', 'false', 43, ''),
(53, 'Godot Engine', 'Die „Godot Engine“ ist eine in sich geschlossene Entwicklungsumgebung mit Editoren und Skriptsprachen für Spiele aller art.', 'https://godotengine.org/', 'teaser_verweis_godotengine.jpg', 'Opensource', 'false', 22, ''),
(54, 'Inkscape', 'Das Vektorgrafikprogramm im quelloffenen und kostenlosen Bereich der Software, das keine wünsche für Knotenpunkt-Verschieber offen lässt.', 'https://inkscape.org/', 'teaser_verweis_inkscape.jpg', 'Opensource', 'false', 17, ''),
(55, 'Gimp', '„The GNU Image Manipulation Programm“ ist ein Programm zum Editieren von Fotos, quasi kann man Fotos so „gimpen“, dass sie wie „gefotoshoppt“ aussehen.', 'https://www.gimp.org/', 'teaser_verweis_gimp.jpg', 'Opensource', 'false', 51, ''),
(56, 'Scribus', 'Die Anwendung „Scribus“ ist eine DTP-Anwendung für angehende Schriftsetzer, welche sich die ersten Erkenntnisse rauf schaffen wollen.', 'https://www.scribus.net/', 'teaser_verweis_scribus.jpg', 'Opensource', 'false', 12, ''),
(57, 'MyPaint', '„MyPaint“ ist eine Zeichen- und Malanwendung, die auf einer unbegrenzten Leinwand schöpferische Fähigkeiten auf den Punkt bringt.', 'https://github.com/mypaint/mypaint/releases', 'teaser_verweis_mypaint.jpg', 'Opensource', 'false', 41, ''),
(58, 'Pencil2D', 'Um Animationen im 2D-Raum zu erzeugen, gibt es viele Anwendungen, nur wenige glänzen mit einer aufgeräumten und leicht zugänglichen Bedienung.', 'https://www.pencil2d.org/', 'teaser_verweis_pencil2d.jpg', 'Opensource', 'false', 4, ''),
(59, 'ephtracy', 'Unter „MagicaVoxel“ finden sich auch noch weite interessante Editoren für 3D-Objekte. Im Speziellen ist „MagicaVoxel“ aber ein Voxel 3D-Programm.', 'https://ephtracy.github.io/', 'teaser_verweis_magicavoxel.jpg', 'Opensource', 'false', 101, ''),
(60, 'Sweet Home 3D', 'Der Innenraumplaner „Sweet Home 3D“ bietet einen großen Funktionsumfang zum Konstruieren von Wohnräumen und sogar ganzen Häusern.', 'http://www.sweethome3d.com/', 'teaser_verweis_sweethome3d.jpg', 'Opensource', 'false', 5, ''),
(61, 'Birdfont', 'Ein Font-Editor mit dem üblichen Funktionsumfang und typischen Exportmöglichkeiten für Fonts glänzt.', 'https://birdfont.org/', 'teaser_verweis_birdfont.jpg', 'Opensource', 'false', 10, ''),
(62, 'Make Human', 'Eine Anwendung zum Generieren von Charakter-Polygonobjekten (Meshes) zur Endverwendung in anderen 3D-Programmen wie Blender.', 'http://www.makehumancommunity.org/', 'teaser_verweis_makehuman.jpg', 'Opensource', 'false', 25, ''),
(63, 'Free Texture Packer', '„Free Texture Packer“ packt viele einzelne Grafiken (Sprites) zu einer einzigen großen Grafik (Sprite Sheet) zusammen, sodass „Game Engines“ diese ressourcenschonend nutzen können.', 'http://free-tex-packer.com/', 'teaser_verweis_freetexturepacker.jpg', 'Opensource', 'false', 106, ''),
(64, 'Stellarium', '„Stellarium“ ist ein quelloffenes und kostenloses Programm, welches am Computer ein komplettes Planetarium simuliert.', 'http://stellarium.org/', 'teaser_verweis_stellarium.jpg', 'Opensource', 'false', 17, ''),
(65, 'FileZilla', 'Um auf „Webspace“ zugreifen zu können, um Dateien auszutauschen, benötigt man ein Programm, welches das „ftp“-Protokoll versteht. „FileZilla“ kann das und noch viel mehr.', 'https://filezilla-project.org/', 'teaser_verweis_filezilla.jpg', 'Opensource', 'false', 134, ''),
(66, 'OBS Studio', 'Um den Bildschirm aufzuzeichnen, zum Beispiel für einen „Stream“ bei diversen Videoplattformen im Internet, ist „OBS Studio“ unverzichtbar.', 'https://obsproject.com/', 'teaser_verweis_obsstudio.jpg', 'Opensource', 'false', 16, ''),
(67, 'Apophysis 7X', '„Apophysis 7X“ ist ein Erzeuger, Editor und Renderer für fraktale Visualisierungen (Flammen), welche zuweilen spektakuläre visuelle Fraktale generiert.', 'https://sourceforge.net/projects/apophysis7x/', 'teaser_verweis_apophysis7x.jpg', 'Opensource', 'false', 19, ''),
(68, 'MeshLab', 'Das quelloffene „MeshLab“ ist ein Programm zur Bearbeitung, Optimierung und Untersuchung von 3D-Hohlkörpermodellen (Meshes) aus 3D-Anwendungen.', 'https://www.meshlab.net/', 'teaser_verweis_meshlab.jpg', 'opensource', 'false', 11, ''),
(69, 'Cyotek Palette Editor', 'Dieses kleine nützliche Programm ermöglicht die Erstellung, das Konvertieren und die Bearbeitung von Farbpaletten für diverse Anwendungen.', 'https://www.cyotek.com/cyotek-palette-editor', 'teaser_verweis_cyotek.jpg', 'Opensource', 'false', 7, ''),
(70, 'Shotcut', 'Für die Bearbeitung von Videos gibt es eine großen Vielzahl an Anwendungen. „Shortcut“ ist ein quelloffener und kostenloser Vertreter aus diesem Spektrum von Anwendungen.', 'https://shotcut.org/', 'teaser_verweis_shotcut.jpg', 'Opensource', 'false', 18, ''),
(71, 'Kdenlive', '„Kdenlive“ ist ein kostenloser quelloffener Videoeditor, der laut Entwicklern auch sehr einfach anzuwenden ist und auch jedem Zweck dient.', 'https://kdenlive.org/', 'teaser_verweis_kdenlive.jpg', 'Opensource', 'false', 24, ''),
(72, 'yt-dl', '„YouTube dl“ macht das, was aller Wahrscheinlichkeit nach der Name verrät: Er lädt Inhalte von „YouTube“ herunter. ob das nun gut oder schlecht ist …?', 'https://yt-dl.org/', 'teaser_verweis_ytdl.jpg', 'Opensource', 'false', 42, ''),
(73, 'AnimeEffects', 'Hierbei handelt es sich um eine Anwendung, mit der 2D-Schlüsselbild-Animationen erzeugt werden können. es gibt sogar Polygon-Netze, laut Entwickler.', 'http://animeeffects.org/', 'teaser_verweis_animeeffects.jpg', 'Opensource', 'false', 2, ''),
(74, 'free cad web', '„Computer Aided Design“ bezeichnet computergestütztes Konstruieren, neben vielen Kostenpflichten Programmen aus diesem Bereich existiert auch noch das quelloffene und kostenlose „freecad“.', 'https://www.freecadweb.org/', 'teaser_verweis_freecad.jpg', 'Opensource', 'false', 25, ''),
(75, 'Sozi', '„Sozi“ ist eine Anwendung um Präsentationen hübsch und professionell aufzuwerten. „Sozi“ ist ein Editor und Abspieler für eben diese Präsentationen.', 'https://sozi.baierouge.fr/', 'teaser_verweis_sozi.jpg', 'Opensource', 'false', 36, ''),
(76, 'Lobbyland', '\"Lobbyland\" ist die Website des ehemaligen fraktionslosen Bundestagsabgeordneten Marco Bülow. er trat zuletzt in die Partei ein und war vormals SPD-Abgeordneter. in seiner Arbeit als Abgeordneter kritisierte er im Bundestag den Profillobbyismus, der die Demokratie zerstört.', 'https://lobbyland.de/', 'teaser_verweise_lobbyland.jpg', 'Politik', 'false', 321, ''),
(77, 'hackr.io', 'Für angehende Programmierer gibt es hier eine große Auswahl an Programmiersprachen, welche man lernen kann.', 'https://hackr.io/', 'teaser_verweise_hackr.io_.jpg', 'Programmierung', 'false', 21, ''),
(78, 'Blindtextgenerator', 'Der „Blindtextgenerator“ bietet eine Auswahl an verschiedenen Blindtexten für die Webseitenentwicklung, wo er noch nicht geschriebene Texte ersetzt.', 'https://www.blindtextgenerator.de/', 'teaser_verweis_blindtextgenerator.jpg', 'Sammlung', 'false', 34, ''),
(79, 'google webfonts helper', 'Beim „google webfonts helper“ sind alle Fonts von „google“ aufgelistet und können für den Gebrauch auf dem eigenen Webserver angepasst und vorbereitet werden.', 'https://google-webfonts-helper.herokuapp.com/fonts', 'teaser_verweis_googlewebfontshelper.jpg', 'Sammlung', 'false', 168, ''),
(80, 'Hero Patterns', 'Eine Sammlung wiederholbarer SVG-Hintergrundmustern, die sie in ihren Webprojekten verwenden können.', 'https://heropatterns.com/', 'teaser_verweis_heropatters.jpg', 'Sammlung', 'false', 3, ''),
(81, 'OpenVDB', 'VDB-Dateien können in 3D-Anwendungen verwendet werden bzw. dort importiert werden und stellen Effekte oder ähnliches zur Verfügung.', 'https://www.openvdb.org/', 'teaser_verweise_openvdb.jpg', 'Sammlung', 'false', 2, ''),
(82, 'Linotype', '„Linotype“ ist die erste Adresse für kommerzielle Schriftarten. neben aktuellen Informationen aus der Schriftarten-Designer-Szene finden sie auch weitere Informationen zu Schriftarten.', 'https://www.linotype.com/', 'teaser_verweis_linotype.jpg', 'Schriftarten', 'false', 8, ''),
(83, 'MyFonts', 'Auf dieser Seite dreht sich alles um Schriftarten, kostenlos für den privaten gebrauch oder kommerzielle Schriftarten zum Kaufen. Zudem kann man hier mit „what the font“ Schriftarten erkennen.', 'https://www.myfonts.com/', 'teaser_verweis_myfonts.jpg', 'Schriftarten', 'false', 54, ''),
(84, 'Libertine Fonts', 'Die „Libertine“ ist eine kostenlose Schriftart mit Serifen und Biolinum ist serifenlos, sie kommt mit Schriftschnitten wie „italic“ und „bold“ daher.', 'https://libertine-fonts.org/', 'teaser_verweis_libertine.jpg', 'Schriftarten', 'false', 86, ''),
(85, 'Font Library', 'Diese Sammlung von Schriftarten und Schriftschnitten veröffentlicht die Schriftdateien unter der „open font license“ (offene Schriftarten Lizenz). die Schriften sind qualitativ hochwertig und können sogar in Webseiten übernommen werden.', 'https://fontlibrary.org/', 'teaser_verweis_fontlibrary.jpg', 'Schriftarten', 'false', 62, ''),
(86, 'the league of moveable type', 'Diese Webseite bietet eine Auswahl exklusiver kostenloser Schriftarten und Schriftschnitte an, die alle unter der „öffentlichen Schriftarten Lizenz“ veröffentlicht wurden.', 'https://www.theleagueofmoveabletype.com/', 'teaser_verweis_leagueofmoveabletype.jpg', 'Schriftarten', 'false', 45, ''),
(87, 'JS Placement', '„jsplacement“ ist eine kleine Anwendung, welche Texturen generiert (\"Normal, Displacement\" ...) bis zu 8192 x 8192 Pixeln, welche dann in 3D-Anwendungen genutzt werden können.', 'https://windmillart.net/?p=jsplacement', 'teaser_verweis_jsplacement.jpg', 'Software', 'false', 43, ''),
(88, 'TAGAP', 'Ein kostenloses Computerspiel, das sehr schön gemacht ist und dem Spieler viele Herausforderungen bietet.', 'https://www.tagap.net/', 'teaser_verweis_tagap.jpg', 'Spiele', 'false', 82, ''),
(89, 'jcgames', 'Hier werden Rollenspiele diskutiert, die in der Regel kostenlos sind und mit Stift und Papier gespielt werden können.', 'https://jcgames.de/', 'teaser_verweis_freierollenspiele.jpg', 'Spiele', 'false', 83, ''),
(90, 'Open Source Game Clones', 'Diese Übersicht listet „Opensource“-Spiele auf, die auf erfolgreichen Spielprinzipien der Vergangenheit und älteren bis jüngeren Gegenwart beruhen.', 'https://osgameclones.com/', 'teaser_verweis_osgameclones.jpg', 'Spiele', 'false', 24, ''),
(91, 'GeneRally', '„GeneRally“ ist ein kostenloses Rennspiel, welches aus einer Draufsicht-Perspektive gespielt wird. Spieler können gegen den Computer oder freunde fahren.', 'https://gene-rally.com/', 'teaser_verweis_generally.jpg', 'Spiele', 'false', 15, ''),
(92, 'Mega Glest', '„Mega Glest“ ein Echtzeitstrategiespiel in einer Fantasiewelt. Dieses „Opensource“-Projekt wird schon viele lang entwickelt und weiterentwickelt.', 'https://megaglest.org/', 'teaser_verweise_megaglest.jpg', 'Spiele', 'false', 25, ''),
(93, 'Shodan', 'Diese Suchmaschine sucht im Prinzip alles, was irgendwie im Internet zugänglich ist.', 'https://www.shodan.io/', 'teaser_verweis_shodan.jpg', 'Suchmaschinen', 'false', 39, ''),
(94, 'AlternativeTo', 'Diese Suchmaschine listet alternativen zu bestimmten Programmen auf, welche sie vielleicht ersetzen wollen.', 'https://www.alternativeto.net', 'teaser_verweis_alternativeto.jpg', 'Suchmaschinen', 'false', 25, ''),
(95, 'cgbookcase', 'Kostenlose PBR-Texturen, um fotorealistische Materialien für 3D-Anwendungen zu kreieren. Alle Inhalte sind 100%ig frei und ohne Bedingungen nutzbar.', 'https://www.cgbookcase.com/', 'teaser_verweise_cgbookcase.jpg', 'Texturenmaterial', 'false', 58, ''),
(96, 'ambientCG', 'Ganz viele PBR-Texturen und Shader usw. für 3D-Anwendungen unter einer \"CC0\"-Lizenz.', 'https://ambientcg.com/', 'teaser_verweise_ambientcg.jpg', 'Texturenmaterial', 'false', 41, ''),
(97, 'Solar Textures', 'Eine umfangreiche Sammlung von Texturen aus dem Sonarsystem erwartet sie hier.', 'https://www.solarsystemscope.com/textures/', 'teaser_verweis_solartextures.jpg', 'Texturenmaterial', 'false', 79, ''),
(98, 'Poly Haven', 'Eine öffentliche Bibliothek für 3D-Inhalte wie HDRI-Bilder, Texturen und Modelle. alles ist 100 % kostenlos und wird unter der „CC0“ veröffentlicht.', 'https://polyhaven.com/', 'teaser_verweis_polyhaven.jpg', 'Texturenmaterial', 'false', 43, ''),
(99, 'textures.com', '„textures.com“ (vormals cgtextures.com) ist ein kostenpflichtiger Dienst, der diverse 3D-Inhalte (vorwiegend Texturen) bereitstellt. Registrierte Benutzer, die keine Zahlungen leisten, haben dennoch Zugriff auf die Inhalte in Höhe von täglich 15 Freien Credits.', 'https://www.textures.com/', 'teaser_verweis_textures.jpg', 'Texturenmaterial', 'false', 46, ''),
(100, 'ambientCG', 'Bei „ambientCG“ gibt es kostenlose und gemeinfreie Materialien für PBR-\"Rendering\". Die Lizenz der Inhalte wird als „CC0“ angegeben.', 'https://ambientcg.com/', 'teaser_verweis_ambientcg.jpg', 'Texturenmaterial', 'false', 50, ''),
(101, 'Quixel', '„Quixel“ ist ein Programm von „Epic Games“ (unreal Engine), das zum texturierten von 3d-Hohlköpermodellen eingesetzt werden kann. Materialien finden sie dafür hier.', 'https://quixel.com/megascans/free', 'teaser_verweis_quixelmegascan.jpg', 'Texturenmaterial', 'false', 43, ''),
(102, 'Texture Lib', 'Diese Sammlung von kostenlosen Texturen betreibt \"Dmitriy Chugai\". Alle Bilder dort sind freigegeben für die kommerzielle wie auch nicht-kommerzielle Nutzung.', 'http://texturelib.com/', 'teaser_verweis_texturelib.jpg', 'Texturenmaterial', 'false', 49, ''),
(103, 'ClipSafari', '\"ClipSafari\" bietet eine große Auswahl an PNG und SVG Dateien für den privaten und kommerziellen Gebrauch, die Lizenz ist \"CC0\"', 'https://www.clipsafari.com/', 'teaser_verweise_clipsafari.jpg', 'Vektormaterial', 'false', 31, ''),
(104, 'OpenClipArt', '\"OpenClipArt\" bietet ganz viele kostenlose Vektorgrafiken für jedweden Zweck. ', 'https://openclipart.org/', 'teaser_verweise_openclipart.jpg', 'Vektormaterial', 'false', 12, ''),
(105, 'Free SVG', 'Ganz viele Vektordateien unter einer \"CC0\"-Lizenz, die unterschiedlicher und schöner nicht sein können.', 'https://freesvg.org/', 'teaser_verweise_freesvg.jpg', 'Vektormaterial', 'false', 16, ''),
(106, 'SVG Silh', 'Vektorgrafiken unter der \"CC0\"-Lizenz für private und kommerzielle Zwecke.', 'https://svgsilh.com/', 'teaser_verweise_svgsilh.jpg', 'Vektormaterial', 'false', 24, ''),
(107, 'Free Images', 'Eine Sammlung an kostenlosen und lizenzfreien Bildern für die private und kommerzielle Nutzung.', 'https://www.freeimages.com/', 'teaser_verweise_freeimages.jpg', 'Vektormaterial', 'false', 9, ''),
(108, 'IgniteMotion', 'Kostenlose Videohintergründe in 4k für diverse Zwecke im Videoschnitt oder für die Webseitenentwicklung.', 'https://www.ignitemotion.com/', 'teaser_verweise_ignitemotion.jpg', 'Videomaterial', 'false', 30, ''),
(109, 'Videvo', 'Ganz viele kostenlose Videos, Clips, Template, Musik und Soundeffekte.', 'https://www.videvo.net/', 'teaser_verweise_videvo.jpg', 'Videomaterial', 'false', 53, ''),
(110, 'Mixkit', '\"Mixkit\" ist eine Seite mit kostenlosen Inhalten für Videografen und Designer, mit kostenlosen Downloads.', 'https://mixkit.co/', 'teaser_verweise_mixkit.jpg', 'Videomaterial', 'false', 7, ''),
(111, 'Mockmagic', '\"Mockmagic\" ist eine Webseite, die beim Erstellen von \"Mockups\" (Attrappen für Designer in diesem Fall) hilft. dabei kann aus einer großen Auswahl kostenloser vorlagen für Laptops, Uhren usw. ausgewählt werden.', 'https://www.mockmagic.com/?ref=producthunt', 'teaser_verweise_mockmagic.jpg', 'Webanwendungen', 'false', 63, ''),
(112, 'Bloom3D', '„Bloom3D“ ist ein einfaches Modellierungswerkzeug für Entwicklung einfacher oder auch komplexerer 3D-Hohlkörperobjekte.', 'https://bloom3d.com/', 'teaser_verweis_bloom3dcom.jpg', 'Webanwendungen', 'false', 51, ''),
(113, 'FontArk', '„FontArk“ ist eine Anwendung, mit der sie im Browser eigene Fonts entwerfen können.', 'https://fontark.net/farkwp/', 'teaser_verweis_fontark.jpg', 'Webanwendungen', 'false', 14, ''),
(114, 'qrcode monkey', '„qrcode monkey“ erzeugt diverse \"QR-Codes\", mit verschiedensten Inhalten wie E-Mail, Adresse usw.', 'https://www.qrcode-monkey.com/de/', 'teaser_verweis_qrcodemonkey.jpg', 'Webanwendungen', 'false', 73, ''),
(115, 'space 2d', '„space 2d“ erzeugt Weltraumhintergründe in beliebiger Auflösung und für alle denkbaren Zwecke.', 'https://www.tyro.github.io/space-2d/', 'teaser_verweis_tyro.github.io_.jpg', 'Webanwendungen', 'false', 12, ''),
(116, 'Super Shapes', '„Super Shapes“ ist eine mathematische Anwendung 3D-Objekte erstellt.', 'https://drajmarsh.bitbucket.io/supershapes.html', 'teaser_verweis_supershapesgen.jpg', 'Webanwendungen', 'false', 86, ''),
(117, 'Word Cloud Generator', '„Word Cloud Generator“ hilft beim Generieren einer Wörterwolke aus eigenem Text bzw. aus eigenen Wörtern.', 'https://www.jasondavies.com/wordcloud/', 'teaser_verweis_wordcloudgenerator.jpg', 'Webanwendungen', 'false', 28, ''),
(118, 'Barcode Generator', 'Der „Barcode Generator“ generiert eine Vielzahl an verschiedenen Barcodes inkl. \"QR-Codes\".', 'https://lindell.me/jsbarcode/generator/', 'teaser_verweis_barcodegenerator.jpg', 'Webanwendungen', 'false', 58, ''),
(119, 'Kapwing', 'Der „Kapwing“ generiert eigene Internet-Memes aus Bildern, die es auszuwählen gibt bzw. selbst hoch geladenen Bildern.', 'https://www.kapwing.com/studio/editor', 'teaser_verweise_memegen.jpg', 'Webanwendungen', 'false', 12, ''),
(120, 'Cool Backgrounds', 'Dies ist ein Generator für verschiedenste Backgrounds, welche sie nach ihrem Geschmack gestalten können.', 'https://coolbackgrounds.io/', 'teaser_verweis_coolbackgrounds.jpg', 'Webanwendungen', 'false', 43, ''),
(121, 'animista', 'Diese Anwendung ermöglicht es, den Code für CSS-Animationen zu generieren und dabei genau anzupassen.', 'https://animista.net/', 'teaser_verweis_animista.jpg', 'Webanwendungen', 'false', 22, ''),
(122, 'triangles', 'Diese Webanwendung erzeugt je nach Einstellungen wunderschöne Dreiecks-Muster.', 'https://msurguy.github.io/triangles/', 'teaser_verweis_trianglepatternmaker.jpg', 'Webanwendungen', 'false', 92, ''),
(123, 'trianglify', 'Diese Webanwendung generiert nach ihren Einstellungen muster in einer Auflösung bis zu 3840 x 3840 Pixeln.', 'https://trianglify.io/', 'teaser_verweis_trianglify.io_.jpg', 'Webanwendungen', 'false', 52, ''),
(124, 'divtable', 'Diese Webanwendung ist eigentlich eine Sammlung diverser Werkzeuge zum Bearbeiten oder generieren von Tabellen oder \"div\"-Strukturen.', 'https://divtable.com/', 'teaser_verweis_table.jpg', 'Webanwendungen', 'false', 49, ''),
(125, 'Sculpfab', 'Diese Webanwendung ist ein vollwertiges „Sculpting“-Werkzeug ähnlich den Anwendungen Blender, ZBrush, Meshmolder und Mudbox.', 'https://labs.sketchfab.com/sculptfab/', 'teaser_verweis_sculptfab.jpg', 'Webanwendungen', 'false', 83, ''),
(126, 'Rainbow Mazes', 'Diese Webanwendung zeichnet prozedurale Labyrinthe, die zudem noch bunt sind.', 'https://rainbowmazes.com/', 'teaser_verweis_ranbowmazes.jpg', 'Webanwendungen', 'false', 76, ''),
(127, 'Vectorizer', 'Dieses Werkzeug ermöglicht die Gestaltung von Mustern bekannt als Guillochen, die sich dann auch herunterladen lassen als SVG oder PNG.', 'http://blackholedesign.com/vectorizer/', 'teaser_verweis_vectorizer.jpg', 'Webanwendungen', 'false', 47, ''),
(128, 'Password Generator', 'Ein sicheres Passwort ist in so unsicheren Zeiten sehr wichtig. wer also ein neues Passwort braucht, sollte diesen Generator benutzen.', 'https://www.experte.com/password-generator', 'teaser_verweis_passwordgen.jpg', 'Webanwendungen', 'false', 48, ''),
(129, 'Nukemap', 'Eine Anwendung, die die Auswirkungen von Nuklearwaffen auf einer Weltkarte demonstriert.', 'https://nuclearsecrecy.com/nukemap/', 'teaser_verweise_nukemap.jpg', 'Webanwendungen', 'false', 26, ''),
(130, 'coolors', 'Mit „coolors.co“ lassen sich Farbschemen für Projekte erstellen, zum Beispiel auch für Webseiten etc.', 'https://coolors.co/', 'teaser_verweis_coolors.jpg', 'Webanwendungen', 'false', 13, ''),
(131, 'Kalender', 'Mit „kalender.com“ lassen sich vielfältige und nützliche Kalender erstellen.', 'https://www.kalender.com/', 'teaser_verweis_kalender.com_.jpg', 'Webanwendungen', 'false', 5, ''),
(132, 'Fantasy Map Generator', 'Mit diesem Generator können sie fantasievolle Landkarten generieren und fantastischen Welten erschaffen.', 'https://azgaar.github.io/fantasy-map-generator/', 'teaser_verweis_azgaarzfantasymapgen.jpg', 'Webanwendungen', 'false', 7, ''),
(133, 'Stripes Generator', 'Mit diesem Generator lassen sich Muster erzeugen, die ausschließlich aus CSS bestehen.', 'https://stripesgenerator.com/', 'teaser_verweis_cssstribesgenerator.jpg', 'Webanwendungen', 'false', 3, ''),
(134, 'Pattern Cooler', 'Mit dieser Webanwendung können sie aus diversen Mustern wählen, diese ihren Bedürfnissen anpassen und herunterladen.', 'https://www.patterncooler.com/', 'teaser_verweis_freeseamlesspatterns.jpg', 'Webanwendungen', 'false', 3, ''),
(135, 'Texturegenerator Online', 'Mit dieser Webanwendung lassen sich eigene prozedurale Texturen generieren.', 'https://cpetry.github.io/texturegenerator-online/', 'teaser_verweis_texturegenerator.jpg', 'Webanwendungen', 'false', 2, ''),
(136, 'waterpipe js', 'Mit dieser Webanwendung lassen sich sehr hübsche und beeindruckende Linienmuster erzeugen.', 'http://dragdropsite.github.io/waterpipe.js/', 'teaser_verweis_smokybackgroundsgenerator.jpg', 'Webanwendungen', 'false', 4, ''),
(137, 'Space 3D', 'Mithilfe dieser Webanwendung können sie eine \"Skybox\" für Weltraumspiele oder was auch immer sie vorhaben, erzeugen.', 'https://tools.wwwtyro.net/space-3d/', 'teaser_verweis_3dbackgroundbox.jpg', 'Webanwendungen', 'false', 1, ''),
(138, 'moddedbeepbox', '\"modbox\" ist ein Werkzeug zum Erstellen und teilen von Chiptune-Melodien. \"modbox\" erweitert die Welt der Musik in ein ganz neues Reich!', 'https://moddedbeepbox.github.io/3.0/', 'teaser_verweis_modbox.jpg', 'Webanwendungen', 'false', 1, ''),
(139, 'Fantasy Cities', 'Um mittelalterliche Städte zu generieren, ist diese Webanwendung sehr praktisch.', 'http://fantasycities.watabou.ru/', 'teaser_verweis_medievalfantasy.jpg', 'Webanwendungen', 'false', 10, ''),
(140, 'mini magic', 'Eine Sammlung von CSS-Animationen, die ihr Webprojekt so richtig aufpeppen.', 'https://www.minimamente.com/project/magic/', 'teaser_verweis_magiceffects.jpg', 'Webdesign', 'false', 1, ''),
(141, 'Underscores', 'Erstellen Sie einfach ein Starter-„theme“ für „WordPress“. dies ist eine gute Grundlage zum Lernen.', 'https://underscores.me/', 'teaser_verweise_underscoresme.jpg', 'Webdesign', 'false', 1, ''),
(142, 'scinexx', '\"scinexx\" ist eine Webseite mit wissenschaftlichen Informationen und Neuigkeiten aus der Welt der Wissenschaft. die Inhalte sind kostenlos und werbefrei zugänglich.', 'https://www.scinexx.de/', 'verweise_teaserbild_scinexx.jpg', 'Wissenschaft', 'false', 1, ''),
(143, 'Anderas Kemper', '\"Andreas Kemper\" ist ein Soziologe und Forscher zum Thema Rassismus, Klassizismus und Gendeismus.', 'https://andreaskemper.org/', 'teaser_verweise_andreas-kemper.jpg', 'Wissenschaft', 'false', 3, ''),
(144, 'yumpu', 'Eine Sammlung von Dokumenten der wichtigsten Stilmittel in der deutschen Sprache.', 'https://www.yumpu.com/de/document/read/10572918/die-wichtigsten-stilmittel-von-a-bis-z-mgf-kulmbach', 'teaser_verweis_sprachstilmittel.jpg', 'Lernen', 'false', 1, ''),
(145, 'Gedankenwelt', 'Ein Artikel, der sich mit den psychologischen Eigenschaften von Faschisten (gemeinhin auch als Nazis bezeichnet) auseinandersetzt.', 'https://gedankenwelt.de/die-psychologischen-eigenschaften-des-faschisten/', 'teaser_verweis_psychefascho.jpg', 'Wissenschaft', 'false', 10, ''),
(146, 'Pressenza', '\"Umberto Eco\" ist ein ital. Schriftsteller (Der Name der Rose) der hier die Merkmale des Ur-Faschismuses erklärt.', 'https://www.pressenza.com/de/2017/10/14-merkmale-des-ur-faschismus-nach-umberto-eco/', 'teaser_verweis_ueurfaschismus.jpg', 'Wissenschaft', 'false', 1, ''),
(147, 'Conversion Tool', 'Mit diesem Online Werkzeug konvertieren Sie Dateien bis zu 100 GB von JSON, XML, CSV und diverse Office-Formate (xlsx, xls, docx, doc, ods und viele mehr), Video- und Audioformate und noch viele mehr in andere Formate.', 'https://conversiontools.io/', 'teaser_verweise_conversiontool.jpg', 'Webanwendungen', 'false', 12, ''),
(148, 'PHP', 'Für alle Programmierer der Programmiersprache PHP ist das die erste Adresse im Internet. Beschreibungen und Erklärungen im Handbuch sind auch in Deutsch verfügbar.', 'https://www.php.net/', 'teaser_verweise_php.jpg', 'Programmierung', 'false', 1, ''),
(149, 'commie.io', 'Diese kleine Webanwendung hilft beim Austausch von Quellcode-Schnipseln. die ganze Anwendung ist öffentlich und mit einem eindeutigen link immer wieder aufrufbar. andere User können Kommentare zu einzelnen Zeilen abgeben.', 'https://commie.io/', 'teaser_verweise_commie.jpg', 'Webanwendungen', 'false', 1, ''),
(150, 'Zitatesammlung', 'Dies ist eine Seite, quasi das Schwesterprojekt zu \"LinkSafe\": meine Zitatesammlung.', 'https://quotes.dum-planet.de', 'teaser_verweise_zitate.jpg', 'Projekte', 'false', 1, ''),
(151, 'MR online', 'Auf dieser Seite werde in englischer Sprache viele Themen der Weltlage und Nationen detailliert geklärt und erklärt.', 'https://mronline.org/', 'teaser_verweise_mronline.jpg', 'Aufklärung', 'false', 97, ''),
(152, 'Clip Studio', '\"Clip Studio\" ist der japanische Hersteller von \"Clip Studio Paint\", einem professionellen Zeichen- und Animationsprogramm für Comic-Künstler. Dies ist ein kostenpflichtiges Programm mit einer kostenlosen Testversion, die günstigste Version gibt es für rund 49 €, dieser fehlen dann vor allem Funktionen für die Comicbucherstellung.', 'https://www.clipstudio.net/de/', 'teaser_verweise_clipstudio.jpg', 'Software', 'false', 7, ''),
(153, 'Nachdenkseiten', 'Auf den Nachdenkzeiten finden Sie aktuelle Informationen, journalistisch fundiert recherchierte Informationen zum tagesaktuellen Geschehen.', 'https://www.nachdenkseiten.de/', 'teaser_verweise_nachdenkseiten.jpg', 'Aufklärung', 'false', 1, ''),
(154, '3D Export', 'Hier gibt es eine Vielzahl von 3D-Modellen zum Kauf oder auch kostenlos. Dabei sind die Modelle für unterschiedliche Zwecke vorsortiert.', 'https://de.3dexport.com/', 'teaser_verweis_3dexport.jpg', '3D-Material', 'false', 1, ''),
(155, 'turbosquid', 'Bei \"Turbosquid\" gibt es 3D-Modelle für vor allem professionelle Designer und Projektbetreibern. es gibt aber auch kostenlose Inhalte, von denen Hobby-Nutzer profitieren können.', 'https://www.turbosquid.com/', 'teaser_verweise_turbosquid.jpg', '3D-Material', 'false', 1, ''),
(156, 'cgtrader', 'Bei \"cgtrader\" gibt es tausende von 3D-Modellen für jedes Bedürfnis. ob für Spiele, Werbung, Unterhaltung oder 3D-Druck. Neben vielen kostenpflichtigen Modellen gibt es natürlich auch eine Auswahl an kostenlosen Inhalten.', 'https://www.cgtrader.com/', 'teaser_verweise_cgtrader.jpg', '3D-Material', 'false', 2, ''),
(157, 'creazilla', '\"creazilla\" bietet nicht nur 3D-Modelle kostenlos an, sondern auch Vektorgrafiken, Silhouetten und Cliparts. Insbesondere interessant sind aber die 3D-Modelle, die allesamt kostenlos angeboten werden.', 'https://creazilla.com/', 'teaser_verweise_creazilla.jpg', '3D-Material', 'false', 1, ''),
(158, 'ColorDesigner', 'Eine kleine Sammlung von Werkzeugen, um Farbpaletten, Verläufe etc. zu erzeugen. insgesamt können sie zwischen 8 verschiedenen Werkzeugen wählen.', 'https://colordesigner.io/', 'teaser_verweise_colordesigner.jpg', 'Webanwendungen', 'false', 1, ''),
(159, 'Wortwuchs', 'Ob rhetorische Stilmittel, Literaturepochen, Grammatik, Poesie oder anderes die deutsche Sprache betreffendes, hier gibt es die Informationen zum Nachlesen.', 'https://wortwuchs.net/', 'teaser_verweise_wortwuchs.jpg', 'Lernen', 'false', 1, ''),
(160, 'Manager', '\"Manager\" ist eine kostenlose software zum Herunterladen, lediglich die Cloudversion ist kostenpflichtig. \"Manager\" ist für die Buchhaltung kleiner Unternehmen gedacht, und auch für den europäischen und deutschen Raum einsetzbar.', 'https://www.manager.io/', 'teaser_verweise_manager.jpg', 'Software', 'false', 7, ''),
(161, 'Timeline', '\"Timeline\" ist eine \"jQuery\"-Erweiterung und bildet eine Zeitachse im Webbrowser nach.', 'https://github.com/ilkeryilmaz/timelinejs', 'teaser_verweise_jquerytimelineplugin.jpg', 'jQuery', 'false', 1, ''),
(162, 'kute.js', '\"kute.js\" ist ein JavaScript Animations-Triebwerk der Zukunft, eingebunden in die eigene Webseite ermöglicht dieses Script beeindruckende Animationen.', 'http://thednp.github.io/kute.js/', 'teaser_verweise_kutejssvgdraw.jpg', 'Javascript', 'false', 1, ''),
(163, 'cssreference.io', 'Unter diesem Verweis finden sie einen visuellen Führer in die Welt des CSS. alles kostenlos und einfach erklärt, zum Lernen und nachmachen.', 'https://cssreference.io/', 'teaser_verweise_css-reference.jpg', 'Webdesign', 'false', 1, ''),
(164, 'XML Notepad', 'Von \"Microsoft\" gibt es hier kostenlos das \"XML Notepad\" eine wahre Erleichterung, wenn es darum geht XML-Dateien zu bearbeiten. Dieses Programm ist selbstverständlich kostenlos.', 'https://microsoft.github.io/XmlNotepad/', 'teaser_verweise_xmlnotepad.jpg', 'Software', 'false', 1, ''),
(165, 'mozilo cms', '\"mozilo cms\" ist ein System für Webseiten, die ohne Datenbank auskommen müssen, es unterstützt dabei jeden kompatiblen, mit PHP betrieben Server.', 'https://www.mozilo.de/', 'teaser_verweise_mozilo.jpg', 'Flat-CMS', 'false', 1, ''),
(166, 'mint press news', 'Hier gibt es unzensierte Informationen zum weltweiten täglichen Geschehen. Die Seite bietet alle Informationen kostenlos an und ist in englischer Sprache.', 'https://www.mintpressnews.com/', 'teaser_verweise_mintpressnews.jpg', 'Aufklärung', 'false', 1, ''),
(167, 'CMSimple', '\"CMSimple\" ist ein Inhalts-Management-System für Webseiten, dabei benötigt es keine Datenbankanbindung an einen Datenbankserver. es reicht ein Server, der PHP unterstützt, und schon fertig.', 'https://www.cmsimple.org/', 'teaser_verweise_cmsimple.jpg', 'Flat-CMS', 'false', 1, ''),
(168, 'Pyrdacor', '\"Pyrdacor\" ist ein Entwickler, der sich den Retrospielen verschrieben hat. so finden sich dort zum Beispiel \"Ambermoon\" und weitere Remakes.', 'https://www.pyrdacor.net/', 'teaser_verweise_pyrdacorremakesretrogames.jpg', 'Spiele', 'false', 1, ''),
(169, 'the base mesh', 'Auf dieser Seite finden sie \"Base Meshes\", die \"uv-unwraped\" sind und sich für Videospiele eigenen. Sie können sogar Wünsche für \"Base Meshes\" äußern.', 'https://thebasemesh.com/model-library', 'teaser_verweise_thebasemesh.jpg', '3D-Material', 'false', 3, ''),
(170, 'Apache NetBeans', '\"NetBeans\" ist eine IDE für überwiegend PHP und Java. \"NetBeans\" ist kostenlos, weil es \"Opensource\" ist. Diese IDE deckt dabei natürlich auch HTML, CSS und Javascript ab. ', 'https://netbeans.apache.org/', 'teaser_verweise_netbeans.jpg', 'Software', 'false', 3, ''),
(171, 'Kids Can Code', '\"Kids Can Code\" bietet für Programmierer der \"Godot Game Engine\" eine Vielzahl hilfreicher Tutorials und Anleitungen zum Umgang mit eben benannter \"Game Engine\".', 'https://kidscancode.org/blog/', 'teaser_verweise_kidscancode.jpg', 'Programmierung', 'false', 1, ''),
(172, 'php.de Wissenssammlung', 'Diese Wissenssammlung rund um PHP ist ein Projekt von \"php.de\" dem deutschsprachigen Forum für PHP. Es werden Grundlagen und fortgeschrittenen Techniken vermittelt.', 'https://php-de.github.io/', 'teaser_verweise_phpdewissen.jpg', 'Programmierung', 'false', 1, ''),
(173, 'David Revoy', '\"David Revoy\" ist ein französischer Künstler, Illustrator und Grafiker, der ausschließlich \"Opensource Software\" in seinem Arbeitsprozess einsetzt.', 'https://www.davidrevoy.com/', 'teaser_verweise_davidrevoy.jpg', 'Künstler', 'false', 1, ''),
(174, 'Meshmolder', 'Bei \"Meshmolder\" handelt sich um eine Software, die kostenlos angeboten wird, aber auch gegen eine kleine Spende ab 6 Dollar in einer Profi-Version (kann neue Inhalte laden) verfügbar ist. Das Programm selbst ermöglicht es, 3D-Modelle zu erstellen und zu bemalen.', 'https://www.meshmolder.com/', 'teaser_verweise_meshmolder.jpg', 'Software', 'false', 2, ''),
(175, 'Font Generator', 'Mit dem \"Font Generator\" lassen sich aus Fonts und eigenen Texte lustige Spielereien für die Sozialen Medien, der wo auch immer Text eingefügt werden kann, erstellen.', 'https://fontgenerator.org/', 'teaser-verweise_font-generator.jpg', 'Webanwendungen', 'false', 0, ''),
(176, '10015', 'Bei dieser Webseite handelt es sich um ein Angebot an vielen verschiedenen Hilfen für Webdesigner, vereint auf einer Webseite.', 'https://10015.io/', 'teaser_verweise_10015IO.jpg', 'Webdesign', 'false', 3, ''),
(177, 'Portable Apps', 'Dieses Angebot richtet sich vor allem an Nutzer von \"Windows\"-Betriebssystemen. Die Apps (Programme) können auf einem USB-Stick überall ausgeführt werden. Dabei lädt man das Hauptprogramm auf einen USB-Stick und installiert dieses darauf.', 'https://portableapps.com/', 'teaser_verweise_portable-apps.jpg', 'Software', 'false', 4, ''),
(178, 'ZBrush Core Mini', '\"ZBrush\" ist ein sehr kostspieliges Programm zum Erstellen von 3D-Modellen. Es ist Industriestandard in der Branche. Die \"Core Mini\" Version ist kostenlos erhältlich, bietet aber einen guten Einstieg in die Mechanismen des Sculptings. (Beim Testen hatte ich keine Exportmöglichkeiten gefunden!)', 'https://zbrushcore.com/mini/', 'teaser_verweise_zbrush_core_mini.jpg', 'Software', 'false', 3, ''),
(179, 'TupiTube', 'Diese Animationssoftware richtet sich eher an Schüler und Lehrer, jedoch kann jeder damit kostenlos Animationen erstellen.', 'https://tupitube.com/', 'teaser_verweise_tupitube.jpg', 'Software', 'false', 7, ''),
(180, 'hotsymbol', 'Auf der Webseite gibt es viele Symbole, die über die Tastatur schwer zu erreichen sind. Auf \"hotsymbol.com\" können Sie sich entsprechende Zeichen auswählen und via kopieren und einfügen in Texte hinzufügen.', 'https://www.hotsymbol.com/', 'teaser_verweise_HotSymbol.jpg', 'Webdesign', 'false', 1, ''),
(181, 'Zettlr', '\"Zettlr\" ist ein kostenloser Markdown-Editor für das 21. Jahrhundert, mit vielen Besonderheiten.', 'https://www.zettlr.com/', 'teaser_verweise_zettlr.jpg', 'Software', 'false', 1, ''),
(182, 'Jim FX\'s | Planetarium', 'Prozedurale Erstellung von 3D-Pflanzen mit der Möglichkeit diese auch zu exportieren und in anderen 3D-Anwendungen zu nutzen.', 'https://plant.jim-fx.com/', 'teaser_verweise_jim-fxs.jpg', 'Webanwendungen', 'false', 17, ''),
(183, 'Aerialod', 'Dieses Programm ist ein Programm, was von den Entwicklern hinter \"MagicaVoxel\" angeboten wird. Es handelt sich dabei um ein Renderprogramm für Höhen-Karten (Height Maps).', 'https://ephtracy.github.io/index.html?page=aerialod', 'teaser_verweise_Aerialod.jpg', 'Software', 'false', 0, 'Dienstag, 7. Juni 2022 um 14:05 Uhr'),
(184, 'Boxshot', '\"Boxshot\" ist eine Software, mit der man Packung-Designs erstellen kann. Unter \"Tools und Extras\" findet man einige Generatoren für Bücher-Cover, Boxen und Screenshot. Lediglich für transparenten Hintergrund und Höhe der Auflösungen wird ein Obolus fällig.', 'https://boxshot.com/3d-book-cover/', 'teaser_verweise_box-book-cover-generator.jpg', 'Webanwendungen', 'false', 0, ''),
(185, 'Brick Block', 'Eine kleine Spielerei im Webbrowser für die Langeweile im Büro von Oskar Stålberg.Zum Ausführen der Anwendung wird die \"Unity-Web-GL\"-Erweiterung benötigt.', 'https://www.oskarstalberg.com/game/house/Index.html', 'teaser_verweise_BrickBlockOskarStålberg.jpg', 'Webanwendungen', 'false', 0, ''),
(186, 'Crossword Compiler', '\"Crossword Compiler\" ist eine Anwendung zum Erstellen von Kreuzworträtseln, Sudokus usw. Die Software ist kostenpflichtig in einem Abo-Modell. ', 'https://www.crossword-compiler.com/de/', 'teaser_verweise_crosswordcompiler.jpg', 'Software', 'false', 0, 'Dienstag, 7. Juni 2022 um 14:14 Uhr'),
(187, 'disposableWebPage', 'Mit \"Disposable\" (Verfügbar) \"Web Page\" können Sie private Webseiten erstellen, die lokal in Ihrem Browser gespeichert werden. Ihr Hauptzweck ist es, einen kurzfristigen Zweck zu erfüllen und Ihnen zu helfen, ein paar Dinge in Gang zu bringen.', 'https://disposablewebpage.com/', 'teaser_verweise_disposableWebPage.jpg', 'Webanwendungen', 'false', 0, 'Dienstag, 7. Juni 2022 um 14:16 Uhr'),
(188, 'Grand Designer', 'Diese Anwendung generiert die Texturen für Planeten inkl. Hintergründen und vielem mehr. Die Einstellungsmöglichkeiten sind dabei sehr umfangreich.', 'http://www.ignishot.com/grand-designer.html', 'teaser_verweise_GrandDesigner.jpg', 'Software', 'false', 0, 'Dienstag, 7. Juni 2022 um 14:19 Uhr'),
(189, 'Hörspielprojekte', 'Wer auf der Suche nach spannender und kostenloser Unterhaltung ist, ist bei \"Hörspielprojekte.de\" richtig aufgehoben. Hier finden sie zahlreiche Hörspiele auf unterschiedlichen Bereichen.', 'https://www.hoerspielprojekt.de/', 'teaser_verweise_hoerspielprojekte.jpg', 'Sammlung', 'false', 0, 'Dienstag, 7. Juni 2022 um 14:21 Uhr'),
(190, 'imo', '\"imo\" ist eine Anwendung für Audio- und Videoanrufe.', 'https://imo.im/', 'teaser_verweise_imo.jpg', 'Software', 'false', 0, 'Dienstag, 7. Juni 2022 um 14:23 Uhr'),
(191, 'MagicaCSG', 'Diese Anwendung ist von den Entwicklern von \"MagicaVoxel\". Es handelt sich um eine Modellier-Software mit integriertem Renderer.', 'https://ephtracy.github.io/index.html?page=magicacsg', 'teaser_verweise_magicacsg.jpg', 'Software', 'false', 0, 'Dienstag, 7. Juni 2022 um 14:25 Uhr');
INSERT INTO `linksafe` (`id`, `titel`, `description`, `url`, `image`, `category`, `advertising`, `clicks`, `date`) VALUES
(192, 'midomi', 'Diese Suchmaschine sucht anhand ihrer stimmlichen Eingabe einen Song.', 'https://www.midomi.com/', 'teaser_verweise_midomi.jpg', 'Suchmaschinen', 'false', 0, 'Dienstag, 7. Juni 2022 um 14:27 Uhr'),
(193, 'Mosaico.io', 'Mit \"Mosaico.io\" lassen sich Layouts für Newsletter gestalten. Diese können via Link auch angepasst und weiterbearbeiet werden.', 'https://mosaico.io/', 'teaser_verweise_Mosaico.jpg', 'Webanwendungen', 'false', 0, 'Dienstag, 7. Juni 2022 um 14:28 Uhr'),
(194, 'neuroflash', 'Bei dieser Anwendung im Web handelt es sich um eine KI, die Anhand von Vorgaben Marketing optimierte Texte verfasst. Die kostenlose Nutzung ist begrenzt auf 2000 Worte/Monat.', 'https://neuroflash.com/', 'teaser_verweise_neuroflash.jpg', 'Webanwendungen', 'false', 0, 'Dienstag, 7. Juni 2022 um 14:30 Uhr'),
(195, 'Online 3D Model Converter', 'Dieser Service bietet die Möglichkeit, 3D-Modelle verschiedener Formate in andere Formate zu konvertieren.', 'http://www.greentoken.de/onlineconv/', 'teaser_verweise_online3dmeshconverter.jpg', 'Webanwendungen', 'false', 0, 'Mittwoch, 8. Juni 2022 um 08:32 Uhr'),
(196, '12ft', '\"12ft\" ist eine Webseite, in der Sie einen Link eingeben können, wo eine \"Paywall\" die Zugänglichkeit stört.', 'https://12ft.io/', 'teaser_verweise_paywallunlocker12ft.jpg', 'Webanwendungen', 'false', 0, 'Mittwoch, 8. Juni 2022 um 08:35 Uhr'),
(197, 'Pinegrow', '\"Pinegrow\" ist ein Webeditor für statische Webseiten bzw. für die Herstellung von Prototypen. Die Anwendung unterstützt diverse CSS-\"Frameworks\".', 'https://pinegrow.com/', 'teaser_verweise_pinegrow.jpg', 'Software', 'false', 0, 'Mittwoch, 8. Juni 2022 um 08:37 Uhr'),
(198, 'Planet', 'Diese Webanwendung generiert einen Planet nach Ihrer Vorstellung. Sie ist von Oskar Stålberg entwickelt worden. Zum Ausführen der Anwendung wird die \"Unity-Web-GL\"-Erweiterung benötigt.', 'https://oskarstalberg.com/game/planet/planet.html', 'teaser_verweise_PlanetOskarStålberg.jpg', 'Webanwendungen', 'false', 0, 'Mittwoch, 8. Juni 2022 um 08:39 Uhr'),
(199, 'Pyxel', '\"Pyxel\" ist ein Pixel-Kunst-Programm, welches für die Erstellung von \"Tile-Maps\" und Animationen nützliche Werkzeuge bietet. Das Programm ist kostenpflichtig. ', 'https://www.pyxeledit.com/index.php', 'teaser_verweise_pyxel.jpg', 'Software', 'false', 0, 'Mittwoch, 8. Juni 2022 um 08:59 Uhr'),
(200, 'Sceelix', '\"Sceelix\" ist eine kostenlose, prozedurale Anwendung zur Erstellung von komplexen 3D-Szenen. ', 'https://sceelix.com/', 'teaser_verweise_sceelix.jpg', 'Software', 'false', 0, 'Mittwoch, 8. Juni 2022 um 09:01 Uhr'),
(201, 'ShapeX', 'Diese Anwendung ermöglicht es, Collagen aus Fotos zu erstellen. Sie können aus einer Vielzahl von Formmasken wählen, die in verschiedene Kategorien unterteilt sind (Tiere, Zahlen, Abstrakt, Text usw.).', 'https://www.reasyze.com/shapex/', 'teaser_verweise_shapeX.jpg', 'Software', 'false', 0, 'Mittwoch, 8. Juni 2022 um 09:03 Uhr'),
(202, 'SimilarSites', 'Diese Suchmaschine sucht für Sie ähnliche Seiten im Internet zusammen.', 'https://www.similarsites.com/', 'teaser_verweise_similarsites.jpg', 'Suchmaschinen', 'false', 0, 'Mittwoch, 8. Juni 2022 um 09:06 Uhr'),
(203, 'Supermailer', '\"Supermailer\" ist eine Anwendung zum Versenden von Newslettern. In der Anwendung können Sie eigene Datenbanken mit Adressaten erstellen, den Newsletter etc. und dann versenden. Die kostenlose Version hat eine Begrenzung der Datensätze.', 'https://www.supermailer.de/', 'teaser_verweise_supermailer.jpg', 'Software', 'false', 0, 'Mittwoch, 8. Juni 2022 um 09:07 Uhr'),
(204, 'TerreSculptor', '\"TerreSculptor\" ist jetzt eines der wichtigsten Geländewerkzeuge, das der Branche zur Verfügung steht. Im Laufe seiner bisherigen Lebensdauer hatte \"TerreSculptor\" mehr als 100.000 Downloads und bleibt wie seine Vorgänger eine kostenlose Software für jede Verwendung.', 'http://www.demenzunmedia.com/home/terresculptor/', 'teaser_verweise_TerreSculptor.jpg', 'Software', 'false', 0, 'Mittwoch, 8. Juni 2022 um 09:09 Uhr'),
(205, 'Who is hosting this?', 'Dieses Webhosting-Checker-Tool gibt detaillierte Eigentums- und Hosting-Informationen über eine Website, einschließlich der IP-Adresse des Hosts, Registrierdetails, Kontaktinformationen und mehr.', 'https://digital.com/best-web-hosting/who-is/', 'teaser_verweise_who-is-hosting-this.jpg', 'Suchmaschinen', 'false', 0, 'Mittwoch, 8. Juni 2022 um 09:11 Uhr'),
(206, 'Wonderdraft', 'Generieren Sie realistische Landmassen verschiedener Typen.\r\nZeichnen Sie Landmassen mit automatisch verschönerten Küsten,\r\nzeichnen Sie Flüsse und Straßen, die mit wenigen Klicks kunstvoll aussehen. Malen Sie Gruppen von Baum- und Bergsymbolen etc.', 'https://www.wonderdraft.net/', 'teaser_verweise_wonderdraft.jpg', 'Software', 'false', 0, 'Mittwoch, 8. Juni 2022 um 09:13 Uhr'),
(207, 'Adalo', 'Mit \"Adalo\" können Sie eigene Applikationen entwickeln, ohne eine Zeile Quelltext schreiben zu müssen. In der kostenlosen Variante können Sie die \"Apps\" dann nur über das \"Adalo\"-Netzwerk aufrufen.', 'https://www.adalo.com/', 'Adalo.jpg', 'Webanwendungen', 'false', 47, ''),
(208, 'BuildFire', '\"BuildFire\" ist eine Webanwendung, mit welcher Sie eigene \"Apps\" für \"Android\" und \"iOS\" entwickeln können. Nach einer kostenlosen Testphase wird die Nutzung kostenpflichtig.', 'https://buildfire.com/', 'buildfire.jpg', 'Webanwendungen', 'false', 25, 'Donnerstag, 16. Juni 2022 um 08:25 Uhr'),
(209, 'AppGyver', '\"AppGyver\" ist die weltweit erste professionelle \"No-Code\"-Plattform, mit der Sie \"Apps\" für alle Formfaktoren erstellen können, einschließlich Mobilgeräte, Desktops, Browser, Fernseher und andere.', 'https://www.appgyver.com/', 'AppGyver.jpg', 'Webanwendungen', 'false', 58, 'Donnerstag, 16. Juni 2022 um 08:30 Uhr'),
(210, 'Artboard Studio', 'Entwerfen, animieren und präsentieren Sie Ihre Projekte mit einer umfangreichen Bibliothek von Modellen direkt im Browser mit Ihrem Team. \"Artboard.Studio\" ist ein \"Mockup\"-Generator mit einem \"Free-Forever\"-Plan.', 'https://artboard.studio/', 'ArtboardStudio.jpg', 'Webanwendungen', 'false', 41, 'Donnerstag, 16. Juni 2022 um 08:32 Uhr'),
(211, 'Bubble', 'Entwicklung ist langsam und teuer. \"Bubble\" ist die leistungsfähigste \"No-Code\"-Plattform zur Erstellung digitaler Produkte. Die kostenlose Nutzung hat Einschränkungen sowie ein Wasserzeichen.', 'https://bubble.io/', 'Bubble.jpg', 'Webanwendungen', 'false', 25, 'Donnerstag, 16. Juni 2022 um 08:35 Uhr'),
(212, 'DeepL Translate', 'Mit \"DeepL Translate\" übersetzen Sie Texte aus \"Word, PDF und anderen Dateiformaten in gegenwärtig 28 andere Sprachen.', 'https://www.deepl.com/translator', 'DeepLTranslate.jpg', 'Webanwendungen', 'false', 25, 'Donnerstag, 16. Juni 2022 um 08:38 Uhr'),
(213, 'Flowlab Game Creator', 'Erstellen Sie Spiele ohne Programmieren: der \"Flowlab Game Creator\" hat die Werkzeuge, die Sie brauchen, alles inklusive und leicht zu erlernen. Alles wird online gespeichert, sodass das Teilen Ihrer Spiele ganz einfach ist. Veröffentlichen und verkaufen Sie Ihre Spiele in den \"App Stores\" von \"Apple\", \"Google\" und \"Amazon\".', 'https://flowlab.io/', 'FlowlabGameCreator.jpg', 'Webanwendungen', 'false', 12, 'Donnerstag, 16. Juni 2022 um 08:40 Uhr'),
(214, 'FotoForensics', '\"FotoForensics\" ist eine Suchmaschine, mit der Sie Fotos auf ihre Echtheit überprüfen können. ', 'https://www.fotoforensics.com/', 'FotoForensics.jpg', 'Suchmaschinen', 'false', 39, 'Donnerstag, 16. Juni 2022 um 08:42 Uhr'),
(215, 'Framer', '\"Framer\" ist eine Webanwendung, mit welcher Sie eine Webseite erstellen können. Der kostenlose Nutzungsplan hat einige Begrenzungen. ', 'https://www.framer.com/', 'Framer.jpg', 'Webanwendungen', 'false', 2, 'Donnerstag, 16. Juni 2022 um 08:45 Uhr'),
(216, 'SVGator', '\"SVGator\" ist eine Webanwendung, mit der Sie ohne Programmierung beeindruckende SVG-Animationen erstellen können. Die kostenlose Nutzung ist limitiert.', 'https://www.svgator.com/', 'FreeSVGAnimationCreator.jpg', 'Webanwendungen', 'false', 3, 'Donnerstag, 16. Juni 2022 um 09:00 Uhr'),
(217, 'Generated Photos', 'Verbessern Sie Ihre kreative Arbeit mit vollständig von KI generierten Fotos. Finden Sie Modellbilder über unsere sortierte und getaggte \"App\" oder integrieren Sie Bilder über die \"API\".', 'https://generated.photos/', 'GeneratedPhotos.jpg', 'Webanwendungen', 'false', 12, 'Donnerstag, 16. Juni 2022 um 09:03 Uhr'),
(218, 'Genially', 'Verwenden Sie \"Genially\", um Inhalte zu erstellen, die Ihr Publikum verblüffen werden! Was auch immer das Projekt ist, \"Genially\" wird für Sie arbeiten.', 'https://genial.ly/', 'Genially.jpg', 'Webanwendungen', 'false', 12, 'Donnerstag, 16. Juni 2022 um 09:04 Uhr'),
(219, 'Hexomatic', 'Erstellen Sie in wenigen Minuten Ihre eigenen \"Bots\", um Daten von jeder Website zu extrahieren, und nutzen Sie über 90 vorgefertigte Automatisierungen, um zeitaufwändige Aufgaben auf Autopilot zu skalieren.', 'https://hexomatic.com/', 'Hexomatic.jpg', 'Webanwendungen', 'false', 45, 'Donnerstag, 16. Juni 2022 um 09:07 Uhr'),
(220, 'Homestyler', 'Ein einfaches und zeitsparendes Online-Innenarchitektur-Werkzeug für Profis und Amateure. Die Basis-Nutzung ist kostenlos und bietet schon ausreichende Möglichkeiten.', 'https://www.homestyler.com/', 'Homestyler.jpg', 'Webanwendungen', 'false', 49, 'Donnerstag, 16. Juni 2022 um 09:08 Uhr'),
(221, 'Hunter', 'Mit \"Hunter\" können Sie in sekundenschnelle professionelle E-Mail-Adressen finden und sich mit den Menschen verbinden, die für Ihr Unternehmen wichtig sind.', 'https://hunter.io/', 'HunterEmail.jpg', 'Suchmaschinen', 'false', 8, 'Donnerstag, 16. Juni 2022 um 09:10 Uhr'),
(222, 'Lumavate', 'Ansprechende und personalisierte digitale Erlebnisse leicht gemacht. Von vorgefertigten Vorlagen bis hin zu unzähligen Integrationen verkürzen wir Ihre Markteinführungszeit drastisch.', 'https://www.lumavate.com/', 'Lumavate.jpg', 'Webanwendungen', 'false', 5, 'Donnerstag, 16. Juni 2022 um 09:12 Uhr'),
(223, 'Minecraft Classic Browser', 'Auf dieser Webseite können Sie \"Minecraft Classic\" kostenlos und uneingeschränkt spielen.', 'https://classic.minecraft.net/?join=kkJwcA9ct0-B0vWN', 'MinecraftClassic.jpg', 'Spiele', 'false', 54, 'Donnerstag, 16. Juni 2022 um 09:14 Uhr'),
(224, 'nandbox', 'Erstellen Sie in wenigen Minuten selbst eine native mobile \"App\", ohne Entwickler einzustellen oder eine Zeile Quelltext zu schreiben. Ein Pool interaktiver Funktionen ist hier, um jedem geschäftlichen oder persönlichen Projekt gerecht zu werden.', 'https://nandbox.com/en/', 'nandboxAppBuilder.jpg', 'Webanwendungen', 'false', 45, 'Donnerstag, 16. Juni 2022 um 09:15 Uhr'),
(225, 'Ninite', '\"Ninite\" ist ein Werkzeug, mit dem Sie sich ein Installationsmedium für Windows herstellen, welches alle benötigten Programme enthält.', 'https://ninite.com/', 'Ninite.jpg', 'Webanwendungen', 'false', 2, 'Donnerstag, 16. Juni 2022 um 09:17 Uhr'),
(226, 'NoCodeAPI', 'Sparen Sie Zeit und Geld, um Ihre \"Google Sheet-, Airtable-, Google Analytics-, Twitter-, Telegram-, Open Graph-API-, MailChimp\"- und über 50 \"Apps\" ohne \"Backend\" einzurichten.', 'https://nocodeapi.com/', 'NoCodeAPI.jpg', 'Webanwendungen', 'false', 6, 'Donnerstag, 16. Juni 2022 um 09:20 Uhr'),
(227, 'Opensource Alternative', 'Entdecken Sie über 300 beliebte Quelloffene-Alternativen zu Ihrem proprietären Software-Portfoilio.', 'https://www.opensourcealternative.to/', 'OpenSourceAlternatives.jpg', 'Suchmaschinen', 'false', 9, 'Donnerstag, 16. Juni 2022 um 09:22 Uhr'),
(228, 'TinyEye', 'Die Produkte von \"TinEye\" für maschinelles Sehen, Bilderkennung und umgekehrte Bildsuche unterstützen Anwendungen, die Ihre Bilder durchsuchbar machen.', 'https://tineye.com/', 'ReverseImageSearch.jpg', 'Suchmaschinen', 'false', 77, 'Donnerstag, 16. Juni 2022 um 09:24 Uhr'),
(229, 'Rytr', '\"Rytr\" ist ein KI-Schreibassistent, der Ihnen hilft, qualitativ hochwertige Inhalte in nur wenigen Sekunden zu einem Bruchteil der Kosten zu erstellen!', 'https://rytr.me/', 'Rytr.jpg', 'Webanwendungen', 'false', 6, 'Donnerstag, 16. Juni 2022 um 09:33 Uhr'),
(230, 'Scam Detector', 'Wenn Sie der Meinung sind, dass eine Website verdächtig ist, können Sie sie gerne mit unserem einzigartigen \"Scam Detector-Website-Validator\" unten überprüfen – geben Sie den Domainnamen ein (mit oder ohne „www.“) und unser Algorithmus sagt Ihnen, wie vertrauenswürdig sie ist.', 'https://www.scam-detector.com/find-scams/', 'ScamDetector.jpg', 'Suchmaschinen', 'false', 8, 'Donnerstag, 16. Juni 2022 um 09:34 Uhr'),
(231, 'Spline', 'Holen Sie sich Ihre 3D-Szenen einfach in Ihre Webprojekte mit \"Spline\".', 'https://spline.design/', 'Spline.jpg', 'Webanwendungen', 'false', 8, 'Donnerstag, 16. Juni 2022 um 09:35 Uhr'),
(232, 'Stage', '\"Stage\" erleichtert Teams und Einzelpersonen Designs\r\nund Prototypen mobiler Apps zu erstellen. Es sind keine Designkenntnisse erforderlich.', 'https://stage.so/', 'Stage.jpg', 'Webanwendungen', 'false', 8, 'Donnerstag, 16. Juni 2022 um 09:37 Uhr'),
(233, 'Goliath Watch', '\"Goliathwatch\" ist ein gemeinnütziger Verein, der sich für eine Wirtschaft einsetzt, die sich in den Dienst von Mensch und Natur stellt – nicht umgekehrt. Wir setzen uns für eine Stärkung unserer Demokratie und gegen Konzernmacht ein.', 'https://goliathwatch.de/', 'teaser_verweise_goliathwatch.jpg', 'Aufklärung', 'false', 100, 'Donnerstag, 16. Juni 2022 um 13:07 Uhr'),
(234, 'Netzwerk Plurale Ökonomie', 'Wir sind Teil der internationalen Bewegung für mehr Vielfalt in der Ökonomik und vernetzen kritische Studierende. Wir engagieren uns für einen zukunftsorientierten Wandel der Wirtschaftswissenschaften. Für neue Impulse in Forschung und Lehre und Politik.', 'https://www.plurale-oekonomik.de/', 'teaser_verweise_pluraleoekonomie.jpg', 'Wissenschaft', 'false', 99, 'Donnerstag, 16. Juni 2022 um 13:09 Uhr'),
(235, 'Unsere Verfassung e.V.', 'Wir leben in einem Staat, in dem sich die Politiker zwar ständig auf das \"Grundgesetz\" berufen, in dem die wesentlichsten Grundsätze und Fragen der Demokratie und des Grundgesetzes aber immer mehr außer Acht gelassen werden.   ', 'https://unsere-verfassung.de/index.htm', 'teaser_verweise_unsereverfassung.jpg', 'Aufklärung', 'false', 97, 'Donnerstag, 16. Juni 2022 um 13:10 Uhr'),
(236, 'Initiative Lieferkettengesetz', 'Ein Bündnis aus mehr als 130 zivilgesellschaftlichen Organisationen. In Deutschland haben wir bereits ein Lieferkettengesetz erkämpft.', 'https://lieferkettengesetz.de/', 'teaser_verweise-lieferkettengesetz.jpg', 'Aufklärung', '', 92, 'Donnerstag, 16. Juni 2022 um 13:11 Uhr'),
(237, 'Watermark Remover', 'Mit dieser Webanwendung entfernen Sie Gitter-Wasserzeichen aus Bildern mithilfe künstlicher Intelligenz.', 'https://www.watermarkremover.io/', 'WatermarkRemover.jpg', 'Webanwendungen', 'false', 5, 'Donnerstag, 16. Juni 2022 um 13:13 Uhr'),
(238, 'Account Killer', 'Wenn Sie Probleme haben, sich an alle Ihre Konten zu erinnern, hat Account Killer eine riesige Liste mit direkten Links zum Löschen Ihres Profils von über 500 verschiedenen Websites.', 'https://www.accountkiller.com/de/home-de', 'ACCOUNTKILLER.COM.jpg', 'Sammlung', 'false', 1, 'Sonntag, 10. Juli 2022 um 07:59 Uhr'),
(239, 'Animal Photo Art Reference', 'Diese Webanwendung hat die Schädelknochen vieler verschiedener Tiere als 3D-Modell gespeichert und sucht Referenzbilder für Tiere. ', 'https://x6ud.github.io/#/', 'AnimalPhotoReference.jpg', 'Webanwendungen', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:04 Uhr'),
(240, 'Animated Drawings', 'Mit dieser Webanwendung können Sie Zeichnungen animieren. Ursprünglich für Kinderzeichnungen entwickelt, kann es aber auch nützlich für Designer und Grafiker sein.', 'https://sketch.metademolab.com/', 'AnimatedDrawings.jpg', 'Webanwendungen', '', 1, 'Sonntag, 10. Juli 2022 um 08:11 Uhr'),
(241, 'Blush', 'Mit \"Blush\" können sie einfach Illustrationen erstellen in einem Stil ihrer Wahl.', 'https://blush.design/de', 'Blush.jpg', 'Webanwendungen', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:14 Uhr'),
(242, 'Boomy', 'Diese Anwendung erstellt unterstützt von einer künstlichen Intelligenz Musik. Sie haben sogar die Möglichkeit zur erstellten Musik eigene Texte einzusingen.', 'https://boomy.com/', 'Boomy.jpg', 'Webanwendungen', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:17 Uhr'),
(243, 'FlutterFlow', 'Mit \"FlutterFlow\" können Sie für unterschiedliche mobile Betriebssysteme \"Apps\" entwickeln, ohne eine Zeile programmieren zu müssen.', 'https://flutterflow.io/', 'FlutterFlow.jpg', 'Webanwendungen', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:19 Uhr'),
(244, 'Fontjoy', 'Das Ziel der Schriftpaarung ist die Auswahl von Schriften, die ein übergreifendes Thema teilen, aber einen angenehmen Kontrast haben.', 'https://fontjoy.com/#', 'Fontjoy.jpg', 'Schriftarten', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:21 Uhr'),
(245, 'FontStruct', 'Mit \"FontStruct\" können Sie eigene Fonts erstellen oder aus bereits erstellten Fonts (Schriftarten) auswählen.', 'https://fontstruct.com/', 'FontStruct.jpg', 'Schriftarten', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:41 Uhr'),
(246, 'Forebears', 'In dieser Suchmaschine finden Sie sehr viele Namen und Plätze.', 'https://forebears.io/', 'Forebears.jpg', 'Suchmaschinen', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:43 Uhr'),
(247, 'Fronty', 'Bild in HTML-CSS umwandeln, der weltweit erste Bild-zu-HTML-Konverter. Holen Sie sich im Handumdrehen den HTML-CSS-Code Ihres Projekts! KI-gestütztes Tool zum Erstellen einer Website in wenigen Minuten.', 'https://fronty.com/', 'Fronty.jpg', 'Webanwendungen', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:46 Uhr'),
(248, 'FutureMe', 'Ich liebe es. Ich habe mir bisher 5 Briefe geschickt und jedes Jahr ist es eine Überraschung. Weil ich es so leicht vergesse. Es wird zu einem so tiefen Reflexionsprozess, dass ich beim Schreiben meistens weine und lache.', 'https://www.futureme.org/', 'FutureMe.jpg', 'Sammlung', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:47 Uhr'),
(249, 'gg.deals', 'Diese Suchmaschine zeigt die aktuellsten, günstigen Preise für Spiele.', 'https://gg.deals/', 'GG.deals.jpg', 'Suchmaschinen', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:50 Uhr'),
(250, 'Hashtag Generator', 'Der beste Instagram-HASHTAG-GENERATOR. Erweiterte Analysen, Hashtag-Sammlungen, Hashtag-Shuffle und es ist KOSTENLOS!', 'https://hashtagstack.com/hashtag-generator', 'HashtagStack.jpg', 'Webanwendungen', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:53 Uhr'),
(251, 'Radio Garden', 'Auf einem Globus können Sie weltweit alle eingetragenen Radiostationen sehen und hören.', 'http://radio.garden/visit/sagard/eHGfQ_hE', 'RadioGarden.jpg', 'Sammlung', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:54 Uhr'),
(252, 'Similar Font', 'Finden Sie ganz einfach kostenlose Alternativen zu Premium-Schriftarten. Finden Sie ganz einfach kostenlose Schriftartalternativen zu über 50 Premium-Schriftarten.', 'https://similarfont.io/', 'SimilarFont.io.jpg', 'Schriftarten', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:57 Uhr'),
(253, 'SVG Artista', 'Diese Webanwendung hilft beim Animieren von SVG-Dateien.', 'https://svgartista.net/', 'SVGArtista.jpg', 'Webanwendungen', 'false', 1, 'Sonntag, 10. Juli 2022 um 08:59 Uhr'),
(254, 'Train Game', '\"Train Game\" ist ein einfaches, aber schönes Eisenbahnspiel.', 'https://objelisks.itch.io/trains-game', 'TrainsGame.jpg', 'Spiele', 'false', 1, 'Sonntag, 10. Juli 2022 um 09:02 Uhr'),
(255, 'Vectary', 'Keine Downloads, keine Codierung – alles im Browser. Mit diesem kostenlosen Werkzeug können Sie 3D-Designs erstellen.', 'https://www.vectary.com/', 'Vectary.jpg', 'Webanwendungen', 'false', 1, 'Sonntag, 10. Juli 2022 um 09:04 Uhr'),
(256, 'You', 'Diese durch künstliche Intelligenz gestützte Suchmaschine achtet ihre Privatsphäre.', 'https://you.com/', 'You.com.jpg', 'Suchmaschinen', 'false', 1, 'Sonntag, 10. Juli 2022 um 09:06 Uhr');

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `linksafe`
--
ALTER TABLE `linksafe`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT für exportierte Tabellen
--

--
-- AUTO_INCREMENT für Tabelle `linksafe`
--
ALTER TABLE `linksafe`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=257;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
